import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const manifestPath = path.resolve('android/app/src/main/AndroidManifest.xml');

if (!fs.existsSync(manifestPath)) {
  console.log('[prepare-android] Android platform not found; run "npm run cap:add:android" first.');
  process.exit(0);
}

let manifest = fs.readFileSync(manifestPath, 'utf8');
const applicationTag = /<application\b([^>]*)>/s;
const match = manifest.match(applicationTag);

if (!match) {
  throw new Error(`[prepare-android] Could not find <application> in ${manifestPath}`);
}

let attrs = match[1];
if (/\bandroid:allowBackup\s*=/.test(attrs)) {
  attrs = attrs.replace(/\bandroid:allowBackup\s*=\s*"[^"]*"/, 'android:allowBackup="false"');
} else {
  attrs += '\n        android:allowBackup="false"';
}

manifest = manifest.replace(applicationTag, `<application${attrs}>`);

// AdMob App ID string — the `android/` platform folder is gitignored and
// regenerated by `cap:add:android`, so this can't just live as a one-off
// manual edit; it has to be reapplied here every time, like allowBackup above.
// See src/app/config/admob.config.ts for the ad UNIT ids (separate from the App ID).
const stringsPath = path.resolve('android/app/src/main/res/values/strings.xml');
if (fs.existsSync(stringsPath)) {
  let strings = fs.readFileSync(stringsPath, 'utf8');
  if (!strings.includes('name="admob_app_id"')) {
    strings = strings.replace('</resources>',
      '    <!--\n' +
      '      AdMob App ID. This is currently Google\'s official public TEST App ID\n' +
      '      (safe to ship during development). Before a production release, create\n' +
      '      this app\'s own App ID in the AdMob console (Apps > Add app) and replace\n' +
      '      the value below — do not reuse another app\'s App ID, that misattributes\n' +
      '      revenue and is against AdMob policy. Ad UNIT ids are configured\n' +
      '      separately in src/app/config/admob.config.ts.\n' +
      '    -->\n' +
      '    <string name="admob_app_id">ca-app-pub-3940256099942544~3347511713</string>\n' +
      '</resources>');
    fs.writeFileSync(stringsPath, strings);
    console.log('[prepare-android] Added AdMob test App ID to strings.xml.');
  }
}

// AdMob requires this meta-data in the manifest or the Google Mobile Ads SDK
// crashes the app on startup. Same regeneration concern as above.
if (!manifest.includes('com.google.android.gms.ads.APPLICATION_ID')) {
  manifest = manifest.replace('</application>',
    '    <!-- AdMob App ID, read from strings.xml (admob_app_id). Required — the\n' +
    '         Google Mobile Ads SDK crashes the app on startup if this is missing. -->\n' +
    '    <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="@string/admob_app_id" />\n' +
    '</application>');
  console.log('[prepare-android] Registered AdMob App ID meta-data in AndroidManifest.xml.');
}

fs.writeFileSync(manifestPath, manifest);
console.log('[prepare-android] Disabled Android backup/restore so uninstall starts a fresh local game wallet. App updates still preserve app data.');

// Regenerate the Android app icon from resources/icon.png on every prepare so a
// designer swapping that file can never leave the native project on a stale icon
// (this previously happened: the shipped APK kept an old icon after icon.png changed).
// The background color matches icon.png's own corner tone so the adaptive-icon
// safe-zone ring blends with the artwork instead of showing a white halo.
const ICON_BACKGROUND_COLOR = '#0f102a';
const capacitorAssetsBin = path.resolve('node_modules/@capacitor/assets/bin/capacitor-assets');
execFileSync(
  process.execPath,
  [capacitorAssetsBin, 'generate', '--android', '--iconBackgroundColor', ICON_BACKGROUND_COLOR, '--iconBackgroundColorDark', ICON_BACKGROUND_COLOR],
  { stdio: 'inherit' }
);
console.log('[prepare-android] Regenerated Android app icon from resources/icon.png.');
