import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const manifestPath = path.resolve('android/app/src/main/AndroidManifest.xml');

if (!fs.existsSync(manifestPath)) {
  console.log('[prepare-android] Android platform not found; run "npm run cap:add:android" first.');
  process.exit(0);
}

let manifest = fs.readFileSync(manifestPath, 'utf8');
const applicationTag = /<application\b([^>]*)>/s;
const match = manifest.match(applicationTag);

if (!match) {
  throw new Error(`[prepare-android] Could not find <application> in ${manifestPath}`);
}

let attrs = match[1];
if (/\bandroid:allowBackup\s*=/.test(attrs)) {
  attrs = attrs.replace(/\bandroid:allowBackup\s*=\s*"[^"]*"/, 'android:allowBackup="false"');
} else {
  attrs += '\n        android:allowBackup="false"';
}

manifest = manifest.replace(applicationTag, `<application${attrs}>`);

// AdMob App ID string — the `android/` platform folder is gitignored and
// regenerated by `cap:add:android`, so this can't just live as a one-off
// manual edit; it has to be reapplied here every time, like allowBackup above.
// See src/app/config/admob.config.ts for the ad UNIT ids (separate from the App ID).
const stringsPath = path.resolve('android/app/src/main/res/values/strings.xml');
if (fs.existsSync(stringsPath)) {
  let strings = fs.readFileSync(stringsPath, 'utf8');
  if (!strings.includes('name="admob_app_id"')) {
    strings = strings.replace('</resources>',
      '    <!--\n' +
      '      AdMob App ID. This is currently Google\'s official public TEST App ID\n' +
      '      (safe to ship during development). Before a production release, create\n' +
      '      this app\'s own App ID in the AdMob console (Apps > Add app) and replace\n' +
      '      the value below — do not reuse another app\'s App ID, that misattributes\n' +
      '      revenue and is against AdMob policy. Ad UNIT ids are configured\n' +
      '      separately in src/app/config/admob.config.ts.\n' +
      '    -->\n' +
      '    <string name="admob_app_id">ca-app-pub-3940256099942544~3347511713</string>\n' +
      '</resources>');
    fs.writeFileSync(stringsPath, strings);
    console.log('[prepare-android] Added AdMob test App ID to strings.xml.');
  }
}

// AdMob requires this meta-data in the manifest or the Google Mobile Ads SDK
// crashes the app on startup. Same regeneration concern as above.
if (!manifest.includes('com.google.android.gms.ads.APPLICATION_ID')) {
  manifest = manifest.replace('</application>',
    '    <!-- AdMob App ID, read from strings.xml (admob_app_id). Required — the\n' +
    '         Google Mobile Ads SDK crashes the app on startup if this is missing. -->\n' +
    '    <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="@string/admob_app_id" />\n' +
    '</application>');
  console.log('[prepare-android] Registered AdMob App ID meta-data in AndroidManifest.xml.');
}

// Google Play Console & AdMob permissions requirement
const requiredPermissions = [
  'android.permission.INTERNET',
  'android.permission.ACCESS_NETWORK_STATE',
  'com.google.android.gms.permission.AD_ID'
];

for (const perm of requiredPermissions) {
  if (!manifest.includes(`android:name="${perm}"`)) {
    manifest = manifest.replace('</manifest>', `    <uses-permission android:name="${perm}" />\n</manifest>`);
    console.log(`[prepare-android] Registered required permission: ${perm}`);
  }
}

fs.writeFileSync(manifestPath, manifest);
console.log('[prepare-android] Disabled Android backup/restore so uninstall starts a fresh local game wallet. App updates still preserve app data.');

// Regenerate the Android app icon from resources/icon.png on every prepare so a
// designer swapping that file can never leave the native project on a stale icon
// (this previously happened: the shipped APK kept an old icon after icon.png changed).
// The background color matches icon.png's own corner tone so the adaptive-icon
// safe-zone ring blends with the artwork instead of showing a white halo.
const ICON_BACKGROUND_COLOR = '#0f102a';
const capacitorAssetsBin = path.resolve('node_modules/@capacitor/assets/bin/capacitor-assets');
execFileSync(
  process.execPath,
  [capacitorAssetsBin, 'generate', '--android', '--iconBackgroundColor', ICON_BACKGROUND_COLOR, '--iconBackgroundColorDark', ICON_BACKGROUND_COLOR],
  { stdio: 'inherit' }
);
console.log('[prepare-android] Regenerated Android app icon from resources/icon.png.');

// Ensure styles.xml has dark navigation and status bar colors
const stylesPath = path.resolve('android/app/src/main/res/values/styles.xml');
if (fs.existsSync(stylesPath)) {
  let styles = fs.readFileSync(stylesPath, 'utf8');
  if (!styles.includes('android:navigationBarColor')) {
    styles = styles.replace('</style>',
      '        <item name="android:statusBarColor">@android:color/transparent</item>\n' +
      '        <item name="android:navigationBarColor">@android:color/transparent</item>\n' +
      '        <item name="android:windowDrawsSystemBarBackgrounds">true</item>\n' +
      '        <item name="android:windowLightStatusBar">false</item>\n' +
      '        <item name="android:windowLightNavigationBar">false</item>\n' +
      '    </style>');
    fs.writeFileSync(stylesPath, styles);
    console.log('[prepare-android] Set dark system bar colors in styles.xml.');
  }
}

// Ensure MainActivity.java has immersive sticky mode configured
const mainActivityPath = path.resolve('android/app/src/main/java/com/admobility/brainrush/MainActivity.java');
if (fs.existsSync(mainActivityPath)) {
  let mainActivity = fs.readFileSync(mainActivityPath, 'utf8');
  if (!mainActivity.includes('setupImmersiveMode')) {
    mainActivity = `package com.admobility.brainrush;

import android.os.Bundle;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.core.view.WindowInsetsControllerCompat;
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setupImmersiveMode();
    }

    @Override
    public void onResume() {
        super.onResume();
        setupImmersiveMode();
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if (hasFocus) {
            setupImmersiveMode();
        }
    }

    private void setupImmersiveMode() {
        WindowCompat.setDecorFitsSystemWindows(getWindow(), false);

        WindowInsetsControllerCompat controller =
            WindowCompat.getInsetsController(getWindow(), getWindow().getDecorView());
        if (controller != null) {
            controller.setSystemBarsBehavior(
                WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
            );
            controller.hide(WindowInsetsCompat.Type.systemBars());
        }
    }
}
`;
    fs.writeFileSync(mainActivityPath, mainActivity);
    console.log('[prepare-android] Ensured immersive sticky mode in MainActivity.java.');
  }
}
